### ISSUE TITLE
Consider Changing to Buffalo

### ISSUE THREAD

**Issue by rexlunae** [dginev/rust-chickenize#1]
I think that it should be "buffalo" instead of "chicken".

**Comment by dginev** [comment]
Good point. Wouldn't it make sense to add an extra function `.buffalo()` and let the dev choose which one to use? 

Pretty easy to generalize the interface further I think.

**Comment by nabijaczleweli** [comment]
You could also add a `chicken: &str` to `chicken()`

**Comment by dginev** [comment]
You mean make the call into `.chicken("buffalo")` ?  Starts getting too funny to be useful haha.

I'd go for:

``` rust
let text = "example here";
text.chicken(); // chicken chicken
text.buffalo(); // buffalo buffalo
text.anonymize("word"); // word word
```

And naturally refactor the chicken and buffalo calls in terms of the generalized anonymize.

**Comment by dginev** [comment]
Btw a small distance from there is to seed the anonymization with a vector of replacements rather than a single one,  so that you can use the chickenize package to produce a [lorem ipsum](https://en.wikipedia.org/wiki/Lorem_ipsum) variant of the input text.

**Comment by dginev** [comment]
Hey @nabijaczleweli thanks for the PR! Do you mind if I use most of it but reorganize a little more in line with the naming scheme I mentioned above? Trying to avoid getting too confusing with the function names :)

**Comment by nabijaczleweli** [comment]
Sure!

FTR, you have push access to my fork's `master` (the PR is from it) so you can push there and it'll show up in the PR making the whole changeset easier to review.

**Comment by dginev** [comment]
Done, and updated to the 0.2.0 crates.io version! Thanks all :+1:
